# Generated by Django 3.0.7 on 2021-01-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password_confirmation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
