# Generated by Django 3.0.7 on 2021-02-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_mutualfund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfund',
            old_name='Fund',
            new_name='fund',
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='risk_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
